sudo: required
language: node_js
node_js:
  - "8"
services:
  - docker

before_install:
  - docker build -t flopivg/docer-react -f Dockerfile.dev .

scripts:
  - docker run flopivg/docker-react yarn test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-1-155458439364"
  bucket_path: "docker-react"
  skip_cleanup: true
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
